### ISSUE TITLE
Comparison to abbrev

### ISSUE THREAD

**Issue by xFA25E** [ymarco/auto-activating-snippets#6]
Hi, I've seen #1 where you mentioned the performance benefit of this package. Do you know how does this package compare to built-in abbrev? It has the exact same capabilities of triggering expansion on character input. Thanks!

**Comment by ymarco** [comment]
You have to call abbrev expansions manually, whether they're hooked to
SPC or TAB, in similar fashion to yasnippet. Here you can do whatever
input sequence you want.

**Comment by minad** [comment]
@ymarco Since I made a small [template/snippet package](https://github.com/minad/tempel) I was looking around and found your package and many [alternatives](https://github.com/minad/tempel#alternatives). I wonder if you are aware of a package which expands abbrevs automatically, not only on if you enter a character which is not a word-consituent as `abbrev-mode` does? Basically like your aas package, but using the abbrev tables instead of its own datastructure?

**Comment by minad** [comment]
Btw, Tempel can be used in conjunction with aas :)

~~~ elisp
(defmacro aas-tempel (&rest template)
  `(lambda () (tempel-insert ',template)))

(aas-set-snippets
 'latex-mode
 :cond #'texmathp
 "//" (aas-tempel "\\frac{" p "}{" p "}"))
~~~

**Comment by ymarco** [comment]
I'm not aware of any, though I think I read somewhere that you can hook
abbrev to post-self-insert-hook to make it like this.

FYI the aas data structure is a keymap. The execution of

(aas-set-snippets 'some-mode
  :cond #'some-cond
  "key1" "expansion1")

basically does

(define-key (gethash 'some-mode aas-keymaps) "key1"
            (lambda () (aas-expand-snippet-maybe "key1" "expansion1" #'some-cond)))

I'm also thinkng of binding an array instead of a lambda — My post-self-insert-hook would need to change slightly, but then I could read the data again an generate menus and docs.

**Comment by minad** [comment]
> FYI the aas data structure is a keymap.

Yes, I've figured that out. This is a nice idea!
